[package]
name = "win32-d3d-template"
version = "0.1.0"
authors = ["Krzysztof Lesiak"]

[dependencies]
winapi = { version = "0.3", features = ["winuser", "minwindef", "windef", "combaseapi", "ntdef", "libloaderapi"] }